apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ozj83qwvc-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ozj83qwvc-dotnet-basic-gitops